replicaCount: 1
app:
  name: garden-api
  profile: stage
  logging:
    enabled: true
  apm:
    enabled: true
mesh:
  enabled: true
image:
  tag: "test"
  version: "test"
resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: garden.stage.dailyhou.se
      paths:
        - path: /
 httpProxy:
  enabled: true
  annotations:
    projectcontour.io/ingress.class: contour
  host: garden.stage.grpc.dailyhou.se
  paths:
    - path: /
externalSecret:
  database:
    enabled: true
    write:
      secretAlias: ohs/db/bucketplace_production/stage
    read:
      secretAlias: ohs/db/bucketplace_production/stage