name: Helm chart Validation

on:
  push:
    branches:
      - feature/OK-37259

# Set env
env:
  # NODE_ENV will be the name of branch
  NODE_ENV: ${{ github.ref == 'refs/heads/feature/**' && 'dev' || 'stage' }}
  AWS_REGION: ap-northeast-2
  ECS_TASK_DEFINITION: task-definition.json

jobs:
  get-image-tag:
    name: get-tag
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ env.NODE_ENV }}
          echo ${{ github.ref }}