name: Helm chart Validation

on:
  push:
    branches:
      - main
      - feature/OK-37259
  pull_request:
    types:
      - review_requested
      - labeled

# Set env
env:
  # If the name of the branch is main, NODE_ENV is stage, otherwise it is dev .
  APP_NAME: bug
  NODE_ENV: ${{ github.ref == 'refs/heads/main' && 'stage' || 'dev' }}
  AWS_REGION: ap-northeast-2
  ECS_TASK_DEFINITION: task-definition.json

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      APP_NAME: bug
    steps:
      - name: checkout-code
        uses: actions/checkout@v2
  get-image-tag:
    name: get-tag
    runs-on: ubuntu-latest
    needs: init
    if: ${{ success() }} && contains( github.event.pull_request.labels.*.name, needs.init.outputs.APP_NAME ) || github.ref == 'refs/heads/main'
    steps:
      - name: test1
        run: |
          echo ${{ github.event.pull_request.labels.*.name }}
          echo ${{ env.APP_NAME }}
      - name: test
        run: |
          echo ${{ env.NODE_ENV }}
          echo ${{ github.ref }}
          echo ${{ env.AWS_REGION }}
      - name: test3
        if: contains( github.event.pull_request.labels.*.name, 'test' ) || github.ref == 'refs/heads/main'
        run: |
          echo ${{ env.NODE_ENV }}
          echo ${{ github.ref }}
          echo ${{ env.AWS_REGION }}