name: Helm chart Validation

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - review_requested
  label:
    types:
     - created

# Set env
env:
  # If the name of the branch is main, NODE_ENV is stage, otherwise it is dev .
  APP_NAME: bug
  NODE_ENV: ${{ github.ref == 'refs/heads/main' && 'stage' || 'dev' }}
  AWS_REGION: ap-northeast-2
  ECS_TASK_DEFINITION: task-definition.json

jobs:
  get-image-tag:
    name: get-tag
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: |
          echo ${{ github.event.pull_request.labels.*.name }}
          echo ${{ env.APP_NAME }}
      - name: test
        if: github.event.pull_request.labels.*.name == ${{ env.APP_NAME }}
        run: |
          echo ${{ env.NODE_ENV }}
          echo ${{ github.ref }}
          echo ${{ env.AWS_REGION }}